# LEARNING NUMPY(Numerical Python)

## IMPORTING LIBRARY AND INITIALISING ARRAY

In [1]:
import numpy as np
print(np.__version__)

2.3.5


In [2]:
array=np.array([1,2,3,4])
print(type(array))

<class 'numpy.ndarray'>


## MULTIDIMENSIONAL ARRAY

In [12]:
array=np.array([['A','B','C'],
                ['D','E','F'],
                ['G','H','I']])
print(array.ndim) #to get the number of dimension of the array
print(array.shape) #to get the shape of the array

array=np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                [['A','B','C'],['D','E','F'],['G','H','I']],
                [['A','B','C'],['D','E','F'],['G','H','I']]])
print(array.ndim)
print(array.shape) # retuens as layers rows and columns 


2
(3, 3)
3
(3, 3, 3)


In [ ]:
#accessing using array[0][0][0] is called chain indexing, In numpy we have multidimesnional indexing array[0,0,0] which is much faster.

## SLICING

In [16]:
array=np.array([['A','B','C'],['D','E','F'],['G','H','I']])
# array[start:end:step]
print(array[1])

['D' 'E' 'F']


In [ ]:
# if we want all the lists printed reversed order

In [17]:
print(array[::-1])

[['G' 'H' 'I']
 ['D' 'E' 'F']
 ['A' 'B' 'C']]


In [20]:
#all the elements of all the rows
print(array[:,0:3])

[['A' 'B' 'C']
 ['D' 'E' 'F']
 ['G' 'H' 'I']]


## ARITHMETIC

In [23]:
# Scalar arithmetic 
array=np.array([1,2,3,4])
print(array+1)
print(array-1)
print(array*2)
print(array/2)
print(array//2)
print(array**2)

[2 3 4 5]
[0 1 2 3]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[0 1 1 2]
[ 1  4  9 16]


In [8]:
# vectorized math functions
#square root

array=np.array([1,4,9,16])
print(np.sqrt(array))

#pi
print(np.pi)
#Area of all the radii
radii=np.array([1,2,3,4])
areas=np.pi*radii**2
print(areas)

[1. 2. 3. 4.]
3.141592653589793
[ 3.14159265 12.56637061 28.27433388 50.26548246]


In [9]:
#Element-wise arithmetic
array1=np.array([1,2,3])
array2=np.array([4,5,6])
print(array1*array2)

[ 4 10 18]


In [13]:
#Comparison operators 
scores=np.array([91,55,100,73,82,64])
print(scores<60)
scores[scores<60]=0
print (scores)

[False  True False False False False]
[ 91   0 100  73  82  64]


## BROADCASTING

In [23]:
#Broadcastin allows Numpy to perform operations on arrays with different shapes by
#virtually expanding dimensions so they match the larger array's shape

#RULE THAT NEEDS TO BE FOLLOWED: dimensions should be same or either one of the array's 
#dimension should be one
array1=np.array([[1,2,3,4]])
array2=np.array([[1],[2],[3],[4]])
print(array1.shape)
print(array2.shape)

print(array1*array2)
print((array1*array2).shape)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
(4, 4)


## AGGREGATE FUNCTIONS

In [31]:
array=np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
print(np.sum(array))
print(np.mean(array))
print(np.std(array)) #returns the standard variation
print(np.var(array)) #returns the variance
print(np.min(array))
print(np.max(array))
print(np.argmin(array)) #position of the minimum number
print(np.argmax(array))

print(np.sum(array,axis=0)) #when axis is zero it just sums all the columns
print(np.sum(array,axis=1)) #when axis is zero it just sums all the rows 

55
5.5
2.8722813232690143
8.25
1
10
0
9


## FILTERING

In [ ]:
#Refers to the process of selecting elements from an array that match a given condition

In [40]:
ages=np.array([[21,17,19,20,16,30,18,65],
             [39,22,15,99,18,19,20,21]])
teenagers=ages[ages<=18]
print(teenagers)
print(ages[(ages>=18) & (ages <65)])

#when filtering if you want to preserve the original shape then use 'where'

adults=np.where(ages>=18,ages,0) #perimeters are condition, array on which operation is to be performed,
                                 #and then the value with which you want to replace non-matching values
print(adults)                    #one can also use -1 or np.nan-(not a number)

[17 16 18 15 18]
[21 19 20 30 18 39 22 18 19 20 21]
[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


## RANDOM NUMBERS

In [57]:
rng=np.random.default_rng()
#to generate random numbers between 1 and 6
print(rng.integers(1,7))
# to increase readability use keyword arguments
print(rng.integers(low=1, high=7))
#If we need a few random numbers i.e. more than one
print(rng.integers(low=1, high=7, size=3)) # this will be stored in one-D array
print(rng.integers(low=1, high=7, size=(3,2))) # this will be stored in two-D array

#We can also set seeds to obtain same results each time
#rng=np.random.default_rng(seed=1)
#FOR FLOATING POINT NUMBERS
print(np.random.uniform()) #uniform means uniform distribution, each value has equal chance to occur(here between 0 and 1)
print(np.random.uniform(low=-1, high=0, size=(3,2)))
#for the seed---> np.random.seed(seed=1)

#FOR ARRAY SHUFFELING
array=np.array([1,2,3,4,5])
rng=np.random.default_rng()
rng.shuffle(array)
print(array)

fruits=np.array(["apple","orange","banana","grapes","watermelon","mangoe","plum"])
fruits=rng.choice(fruits, size=(3,3)) #selecting 3 random fruits
print(fruits)

3
3
[1 1 3]
[[1 5]
 [5 5]
 [4 4]]
0.6939631214002928
[[-0.81558648 -0.82850488]
 [-0.23932917 -0.77709891]
 [-0.04517051 -0.90220523]]
[5 4 3 2 1]
[['orange' 'mangoe' 'grapes']
 ['orange' 'mangoe' 'banana']
 ['banana' 'mangoe' 'orange']]
